name: iptv-playlist-static

services:
  playlist-static:
    image: nginx:alpine
    container_name: playlist-static
    restart: always
    init: true
    network_mode: host
    volumes:
      - ./published:/usr/share/nginx/html:ro
      - ./nginx/playlist-static.conf:/etc/nginx/conf.d/default.conf:ro
