FROM python:3.12-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app /app/app
COPY healthcheck.py /app/healthcheck.py

CMD ["python", "-m", "app.main"]
